### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Emmett-Culhane**
shell scripts and documentation

### CODE REVIEW

**Comment by bkj** [comment]
@Emmett-Culhane  Whats the deal with the following files in `cronjobs`?

```
run-add-otc-flag.py
run-halts-process.sh
run-suspensions-scrape.sh
run-xbrl.sh
xbrl-wrapper.sh
run-parse.sh
```

They don't get called from the `_run-all.sh` script ATM

**Comment by bkj** [comment]
What's the deal with the following scripts from `cronjobs`?

```
run-halts-process.sh
run-otc-enrich.sh
run-suspensions-scrape.sh
```

They don't seem to be getting run anywhere.  Remove if that's the case.

**Comment by bkj** [comment]
- [ ] Add a short description to the top of every script

**Comment by Emmett-Culhane** [comment]
The halts process shell was missing so thats a good catch, I added it back in. Run-otc-enrich is deprecated so I removed it. The sec suspensions script is called inside of the run-halts-process shell that I added back in so that is correct. 

When you say add a short description to the top of every script do you mean every python script, or every shell script. Every shell besides run-halts-process and sec-suspensions have documentation at the top. I will add in for those and then include for the python scripts also.

**Comment by bkj** [comment]
Longer descriptions are good for the shell scripts.  1-2 sentences at the
top of every script is useful, since the names are not always obvious.

You can do something like a half sentence description, plus input, output,
and relevant parameters.

**Pull request closed without merging**
